# mobile-auto export: source=mobile/scripts/android/EXAMPLE-1-buy-250-eur.yaml source_sha256=e62ae5223852fb8e5331c8bd0e815dd2706bc8e6b4589d3176c3febba47c52da content_sha256=9dc9d3d90bd4d9f249ebe5a1c5d70e7a5e18b8f9de1e846545ad3f6d67e2dd7e
"""Step definitions of EXAMPLE-1 buy-250-eur on android: Buy 250 EUR within the daily limit.

Generated by mobile-auto test export from the scenario script; each line from
the recording carries the recorded call. Edit them here; an edited file is
not overwritten by the next export.
"""
from behave import given, then, when
from appium.webdriver.common.appiumby import AppiumBy
from mobiletest import assert_text, assert_visible, by_text, screenshot, secret, swipe, tap, type_text


@given("the customer signs in as uat-fx-01")
def step_01_the_customer_signs_in_as_uat_fx_01(context):
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/username").send_keys("uat-fx-01") (line 2)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/username"), "uat-fx-01")
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/password").send_keys(<password field, value withheld>) (line 4)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/password"), secret("MOBILE_SECRET_PASSWORD"))
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Login").click() (line 6)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Login"), fallbacks=[(AppiumBy.ID, "com.bank:id/login")])
    assert_visible(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Foreign exchange"), timeout=15)
    screenshot(context.driver, "signed in")


@given("the customer opens the foreign exchange screen")
def step_02_the_customer_opens_the_foreign_exchange_screen(context):
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Foreign exchange").click() (line 8)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Foreign exchange"))
    assert_visible(context.driver, (AppiumBy.ID, "com.bank:id/amount"), timeout=15)
    screenshot(context.driver, "foreign exchange screen")


@when("the customer buys 250 EUR")
def step_03_the_customer_buys_250_eur(context):
    # recorded: swipe from (540, 1800) to (540, 1080) over 750 ms (line 9)
    swipe(context.driver, start=(50, 75), end=(50, 45), duration_ms=750)
    # recorded: tap at (190, 1210) held 100 ms (line 10)
    tap(context.driver, by_text("EUR", role="text"))
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/amount").send_keys("100") (line 12)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/amount"), "250")
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Confirm").click() (line 14)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Confirm"))
    assert_visible(context.driver, (AppiumBy.ID, "com.bank:id/total"), timeout=15)
    screenshot(context.driver, "confirmation screen")


@then("the confirmation shows 250.00 EUR")
def step_04_the_confirmation_shows_250_00_eur(context):
    assert_text(context.driver, (AppiumBy.ID, "com.bank:id/total"), fallbacks=[by_text("Total", role="text")], contains="250.00 EUR", timeout=15)
    screenshot(context.driver, "250 EUR confirmation")
