# mobile-auto export: source=mobile/segments/android/EXAMPLE-1-over-daily-limit-usd.yaml source_sha256=121186e80fb5fae08d49b94a164fd456f57c4e7b7e02baaf377ab483f93c6e1a content_sha256=3fc2bd420f0ea7c0a50fd4cf401f88e1caa9481ef8acc0a10ba62b60c060795f
"""Step definitions of EXAMPLE-1 over-daily-limit-usd on android: Buying 50001 USD over the daily limit is refused.

Generated by mobile-auto test export from the scenario script; each line from
the recording carries the recorded call. Edit them here; an edited file is
not overwritten by the next export.
"""
from behave import given, then, when
from appium.webdriver.common.appiumby import AppiumBy
from mobiletest import assert_not_visible, assert_visible, by_text, screenshot, secret, tap, type_text


@given("the customer signs in as uat-fx-01")
def step_01_the_customer_signs_in_as_uat_fx_01(context):
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/username").send_keys("uat-fx-01") (line 2)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/username"), "uat-fx-01")
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/password").send_keys(<password field, value withheld>) (line 4)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/password"), secret("MOBILE_SECRET_PASSWORD"))
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Login").click() (line 6)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Login"), fallbacks=[(AppiumBy.ID, "com.bank:id/login")])
    assert_visible(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Foreign exchange"), timeout=15)
    screenshot(context.driver, "signed in")


@given("the customer opens the foreign exchange screen")
def step_02_the_customer_opens_the_foreign_exchange_screen(context):
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Foreign exchange").click() (line 8)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Foreign exchange"))
    assert_visible(context.driver, (AppiumBy.ID, "com.bank:id/amount"), timeout=15)
    screenshot(context.driver, "foreign exchange screen")


@when("the customer buys 50001 USD")
def step_03_the_customer_buys_50001_usd(context):
    # recorded: tap at (190, 1210) held 100 ms (line 9)
    tap(context.driver, by_text("USD", role="text"))
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/amount").send_keys("50001") (line 11)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/amount"), "50001")
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Confirm").click() (line 13)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Confirm"))
    assert_visible(context.driver, (AppiumBy.ID, "com.bank:id/message"), timeout=15)
    screenshot(context.driver, "refusal screen")


@then("the message Amount exceeds your daily limit is shown")
def step_04_the_message_amount_exceeds_your_daily_limit_is_sho(context):
    assert_visible(context.driver, by_text("Amount exceeds your daily limit"), timeout=15)


@then("no purchase is confirmed")
def step_05_no_purchase_is_confirmed(context):
    assert_not_visible(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Purchase confirmed"))
    screenshot(context.driver, "50001 USD refused")
