# mobile-auto export: source=mobile/suites/EXAMPLE-1/android.yaml source_sha256=98581449b22d13db4eff19b4e1caab626e89721cad17c97fd281d625acefcf5d content_sha256=4db0d14b90cc34124c3d63a6481cd88772090e2efd69f443f5f46f51608c058e
"""Step definitions of EXAMPLE-1 on android.

Generated by mobile-auto test export from the suite. Edit them here; an
edited file is not overwritten by the next export.
"""
from behave import given, then, when
from appium.webdriver.common.appiumby import AppiumBy
from mobiletest import assert_not_visible, assert_text, assert_visible, by_text, screenshot, tap, type_text
from segments.android.seg_login import seg_login
from segments.android.seg_select_currency import seg_select_currency


@given("the customer is signed in")
def step_the_customer_is_signed_in(context):
    seg_login(context.driver, username=context.data['username'])


@given("the customer is on the foreign exchange screen")
def step_the_customer_is_on_the_foreign_exchange_screen(context):
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Foreign exchange"))


@when("the customer buys {amount} {currency}")
def step_the_customer_buys(context, amount, currency):
    seg_select_currency(context.driver, currency=currency)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/amount"), amount)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Confirm"))


@then("the confirmation shows {expected_total}")
def step_the_confirmation_shows(context, expected_total):
    assert_text(context.driver, (AppiumBy.ID, "com.bank:id/total"), fallbacks=[by_text("Total", role="text")], contains=expected_total, timeout=15)
    screenshot(context.driver, f"{context.row['example']} confirmation")


@then("the message {expected_message} is shown")
def step_the_message_is_shown(context, expected_message):
    assert_visible(context.driver, by_text(expected_message), timeout=15)


@then("no purchase is confirmed")
def step_no_purchase_is_confirmed(context):
    assert_not_visible(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Purchase confirmed"))
    screenshot(context.driver, f"{context.row['example']} refused")
