# mobile-auto export: source=mobile/scripts/android/EXAMPLE-1-buy-100-usd.yaml source_sha256=935bcc17905a4e43e29be600f2dade2f0b8da6911036a67dcea6487cee798ee1 content_sha256=3a99871a491a1d7421dfb5f8862ec60f315d6d7fd62e8c909e70fea1bc339a13
"""Step definitions of EXAMPLE-1 buy-100-usd on android: Buy 100 USD within the daily limit.

Generated by mobile-auto test export from the scenario script; each line from
the recording carries the recorded call. Edit them here; an edited file is
not overwritten by the next export.
"""
from behave import given, then, when
from appium.webdriver.common.appiumby import AppiumBy
from mobiletest import assert_text, assert_visible, by_text, screenshot, secret, swipe, tap, type_text


@given("the customer signs in as uat-fx-01")
def step_01_the_customer_signs_in_as_uat_fx_01(context):
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/username").send_keys("uat-fx-01") (line 2)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/username"), "uat-fx-01")
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/password").send_keys(<password field, value withheld>) (line 4)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/password"), secret("MOBILE_SECRET_PASSWORD"))
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Login").click() (line 6)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Login"), fallbacks=[(AppiumBy.ID, "com.bank:id/login")])
    assert_visible(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Foreign exchange"), timeout=15)
    screenshot(context.driver, "signed in")


@given("the customer opens the foreign exchange screen")
def step_02_the_customer_opens_the_foreign_exchange_screen(context):
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Foreign exchange").click() (line 8)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Foreign exchange"))
    assert_visible(context.driver, (AppiumBy.ID, "com.bank:id/amount"), timeout=15)
    screenshot(context.driver, "foreign exchange screen")


@when("the customer buys 100 USD")
def step_03_the_customer_buys_100_usd(context):
    # recorded: swipe from (540, 1800) to (540, 1080) over 750 ms (line 9)
    swipe(context.driver, start=(50, 75), end=(50, 45), duration_ms=750)
    # recorded: tap at (190, 1210) held 100 ms (line 10)
    tap(context.driver, by_text("USD", role="text"))
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/amount").send_keys("100") (line 12)
    type_text(context.driver, (AppiumBy.ID, "com.bank:id/amount"), "100")
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Confirm").click() (line 14)
    tap(context.driver, (AppiumBy.ACCESSIBILITY_ID, "Confirm"))
    assert_visible(context.driver, (AppiumBy.ID, "com.bank:id/total"), timeout=15)
    screenshot(context.driver, "confirmation screen")


@then("the confirmation shows 100.00 USD")
def step_04_the_confirmation_shows_100_00_usd(context):
    assert_text(context.driver, (AppiumBy.ID, "com.bank:id/total"), fallbacks=[by_text("Total", role="text")], contains="100.00 USD", timeout=15)
    screenshot(context.driver, "100 USD confirmation")
