# mobile-auto export: source=mobile/segments/android/seg-select-currency.yaml source_sha256=45e3205b20c0244f5113aa3bbab6e33647ed17591f9360a0e448368506641486 content_sha256=480a3bde90ef6b176ed4622866317f1790ec81ecb3b8567aa64d03e87253972d
"""Segment seg-select-currency: Pick a currency on the foreign exchange screen

Generated by mobile-auto test export from the recorded segment; every line
from the recording carries the recorded call. Edit it here; an edited file is
not overwritten by the next export.
"""
from appium.webdriver.common.appiumby import AppiumBy
from mobiletest import by_text, tap


def seg_select_currency(driver, currency="USD"):
    # recorded: driver.find_element(by=AppiumBy.XPATH, value="//android.widget.TextView[@text=\"USD\"]").click()
    tap(driver, by_text(currency, role="text"))
