# mobile-auto export: source=mobile/segments/android/seg-login.yaml source_sha256=6f01f06ae8440b0520c38805271a52791cfeb1db07731f2880ef14b4d4c4a51e content_sha256=2f8e14731526193eef77296a07290fecd57034deec227237144db442d1e37b16
"""Segment seg-login: Sign in from the launch screen to the home screen

Generated by mobile-auto test export from the recorded segment; every line
from the recording carries the recorded call. Edit it here; an edited file is
not overwritten by the next export.
"""
from appium.webdriver.common.appiumby import AppiumBy
from mobiletest import by_text, secret, tap, type_text, visible


def seg_login(driver, username="tester01"):
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/username").send_keys("tester01")
    type_text(driver, (AppiumBy.ID, "com.bank:id/username"), username)
    # recorded: driver.find_element(by=AppiumBy.ID, value="com.bank:id/password").send_keys(<password field, value withheld>)
    type_text(driver, (AppiumBy.ID, "com.bank:id/password"), secret("MOBILE_SECRET_PASSWORD"))
    # recorded: driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Login").click()
    tap(driver, (AppiumBy.ACCESSIBILITY_ID, "Login"), fallbacks=[(AppiumBy.ID, "com.bank:id/login"), by_text("Log in", role="button")])
    if visible(driver, by_text("Not now"), timeout=3):
        tap(driver, by_text("Not now"))
